INSERT INTO public.conta (ID_CONTA, CLIENTE_CONTA, PRODUTO_CONTA, PRECO_TOTAL)
VALUES (RANDOM_UUID(), 'Gilso', 'shampoo 500ml', 10);
INSERT INTO public.conta (ID_CONTA, CLIENTE_CONTA, PRODUTO_CONTA, PRECO_TOTAL)
VALUES (RANDOM_UUID(), 'Moises', 'condicionador 500ml', 30);
INSERT INTO public.conta (ID_CONTA, CLIENTE_CONTA, PRODUTO_CONTA, PRECO_TOTAL)
VALUES (RANDOM_UUID(), 'Eliane', 'sabao 50ml', 5);
INSERT INTO public.conta (ID_CONTA, CLIENTE_CONTA, PRODUTO_CONTA, PRECO_TOTAL)
VALUES (RANDOM_UUID(), 'Gertrude', 'água 500ml', 1);
INSERT INTO public.conta (ID_CONTA, CLIENTE_CONTA, PRODUTO_CONTA, PRECO_TOTAL)
VALUES (RANDOM_UUID(), 'Ramirez', 'ração 500g', 100);